function c2150000.initial_effect(c)
	BiDiu(c)
	local e=Effect.CreateEffect(c)
	e:SetType(EFFECT_TYPE_FIELD)
	e:SetCode(EFFECT_SET_POSITION)
	e:SetRange(LOCATION_MZONE)
	e:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e:SetValue(POS_FACEUP_DEFENSE)
	e:SetTarget(c2150000.fNoBidiuAtk)
	c:RegisterEffect(e)
	e=e:Clone()
	e:SetCode(EFFECT_SET_ATTACK_FINAL)
	e:SetValue(0)
	e:SetTarget(c2150000.fNoBidiu)
	c:RegisterEffect(e)
	e=e:Clone()
	e:SetCode(EFFECT_SET_DEFENSE_FINAL)
	c:RegisterEffect(e)
	e=Effect.CreateEffect(e)
	e:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e:SetCode(EVENT_LEAVE_FIELD)
	e:SetRange(255)
	e:SetOperation(c2150000.oLeave)
	c:RegisterEffect(e)
end
function c2150000.fNoBidiuAtk(e,c)
	return c:IsFaceup() and not c:IsSetCard(0x215)
end
function c2150000.fNoBidiu(e,c)
	return not c:IsSetCard(0x215)
end
function c2150000.oLeave(e)
	local h=e:GetHandler()
	local g=Duel.GetMatchingGroup(c2150000.fNoBidiu,0,LOCATION_MZONE,LOCATION_MZONE,nil)
	local c=g:GetFirst()
	while c do
		e=Effect.CreateEffect(h)
		e:SetType(EFFECT_TYPE_SINGLE)
		e:SetCode(EFFECT_SET_ATTACK_FINAL)
		e:SetRange(LOCATION_MZONE)
		e:SetValue(0)
		e:SetReset(RESETS_STANDARD+RESET_PHASE+PHASE_END, 2)
		c:RegisterEffect(e)
		e=e:Clone()
		e:SetCost(EFFECT_SET_DEFENSE_FINAL)
		c:RegisterEffect(e)
		c=g:GetNext()
	end
end
